[package]
name = "loadtest"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "loadtest"
path = "src/main.rs"

[dependencies]
goose = { version = "0.18", default-features = false, features = [
    "rustls-tls",
] }
serde_json = "1.0.140"
tokio = { version = "1.45.1", features = ["full"] }
